PoCInnovation/Workshops

- security/xss/03-xss-email/chall.html
- security/xss/04-xss-bypass/chall.html
Added 2 xss challenges
- payload must match email regex
- payload must match email regex but not match the "flag" word
> Added XSS email&bypass

- software/13.Rust/README.md
- software/13.Rust/SETUP.md
Added the Workshop Rust folder, with its Readme and Setup.
> Creation of the Readme and Setup of the Rust workshop. First version.

- software/01.React/README.md
- software/01.React/SETUP.md
This PR marks the renew of the React Workshop.
It is now in Typescript and it uses Material UI as dependency.
> 01.React: Renew of the React workshop

- software/25.Flutter/README.md
- software/25.Flutter/SETUP.md
> 25.flutter

- software/17.gRPC/README.md
- software/17.gRPC/SETUP.md
- SETUP updates to match newest versions
- Code & commands adapted with the newest `protoc` and `go` versions
- Typos and subject explanations
> Fixes for 17.gRPC

- software/02.Go/README.md
- software/02.Go/SETUP.md
- software/02.Go/src/controllers/controllers.go
- software/02.Go/src/go.mod
- software/02.Go/src/main.go
- software/02.Go/src/middlewares/middlewares.go
- software/02.Go/src/models/user.go
- software/02.Go/src/routes/routes.go
- Subject refactored (links, typos...)
- Given code updated accordingly
- SETUP updated for the latest Go version
> Fixes for 02.Go

- software/07.Expo/README.md
- software/07.Expo/SETUP.md
- SETUP updated to match new versions & related problematics
- Subject updated (typos, links, code for newest versions...)
> Fixes for 07.Expo

- software/01.React/SETUP.md
- software/03.Prisma/SETUP.md
- software/07.Expo/SETUP.md
- software/09.Svelte/README.md
- software/09.Svelte/SETUP.md
- software/10.Neo4j/SETUP.md
- software/12.GraphQL-Apollo/SETUP.md
- software/14.Vercel/SETUP.md
- software/15.Svelte-Epytodo/SETUP.md
- software/21.Serverless/SETUP.md
- Subject and setup updated to match latest versions
- First and second steps switch to have to more logical difficulty order
-  UI library added instead of pure CSS
- Typos and refactoring with better documentation
> Fixes for 09.Svelte

- software/08.Typescript/README.md
- software/08.Typescript/SETUP.md
> refactor: workshop express README

- software/29.Flask/README.md
- software/29.Flask/SETUP.md
- software/29.Flask/src/db.sql
- New workshop added: Flask with MySQL
- Create a simple backend in Python with Flask
- Interact with a database
- Discover RESTful concepts
> 29.Flask: New workshop

- .gitignore
- software/01.React/README.md
- software/02.Go/README.md
- software/03.Prisma/README.md
- software/04.Docker/README.md
- software/07.Expo/README.md
- software/08.Express/README.md
- software/16.Rust-Tetra/README.md
- software/18.Kafka/README.md
- software/20.Kubernetes/README.md
- software/21.Serverless/README.md
- software/22.Encore/README.md
- software/24.Git_GitHub/Git/README.md
- software/24.Git_GitHub/GitHub/README.md
- software/25.Flutter/README.md
- software/25.Flutter/SETUP.md
- software/28.Gin/README.md
- software/29.Flask/README.md
- software/README.md
- Typos fixed
- Missing workshops in the global README
> soft: Fixing typos and missing elements

- ai/Regression_logistique/1. Python & Numpy Basiques.ipynb
- ai/Regression_logistique/2.regression_logistic.ipynb
> Ai translations

- ai/Convolution/1.fashion_mnist.ipynb
- ai/Convolution/2.mnist.ipynb
- ai/README.md
- ai/Tensorflow/1.house_price.ipynb
- ai/Tensorflow/2.fashion_mnist.ipynb
- ai/Tensorflow/3.handwritten_digits.ipynb
Translated Tensorflow and Convolution to english and updated README
> [FIX] readme and translations for two workshops

- software/26.SpaceInvaders_Starton/README.md
- software/26.SpaceInvaders_Starton/SETUP.md
- New software workshop: connect a game to the blockchain with Starton
> 26.Space Invaders with Starton: New software workshop

- ai/Convolution/1.fashion_mnist.ipynb
- ai/Convolution/2.mnist.ipynb
- Removed incorrect explanation of why we need to reshape our data
- Removed spoiler-code at the end of the first notebook which solves the first exercise
> [FIX] convolution markdown

- ai/Reinforcement_Learning/Reinforcement_Learning.ipynb
Minor changes to workshop because of new gym update
> [FIX] ai - gym version fixes

- .github/workflows/ markdown-links.config.json
- .github/workflows/check-markdown-links.yml
GitHub Action added to check for dead links in Markdown files
> GitHub Action to check dead links in Markdown files

- software/24.Git_GitHub/Git/README.md
> fix(soft-24.Git_GitHub): Bonus links for Git

- ai/DQN/dqn.ipynb
Fixed notebook to be compatible with most recent version of gym
> [ADD] gym update fixes

- ai/Minitorch/workshop_minitorch.ipynb
:warning: Fixed typos
- Basically
- Know / Now
- Its / It's
> fix: minitorch typos

- p2p/5.Create_an_ERC-20/README.md
- p2p/5.Create_an_ERC-20/SETUP.md
- p2p/5.Create_an_ERC-20/Solidity.md
- p2p/5.Create_an_ERC-20/utils/.env
- p2p/5.Create_an_ERC-20/utils/ERC20.t.sol
- p2p/5.Create_an_ERC-20/utils/IERC20.sol
> P2P: ERC20 Workshop

- software/06.Nest/README.md
> Update nesjs README.md

- software/20.Kubernetes/README.md
Fixed path in k8s deployment step.
> fix: spec.template.matchLabels.app to spec.selector.matchLabels.app

- p2p/5.Create_an_ERC-20/README.md
> feat(p2p): add explanations to erc20: step 2 workshop

- p2p/5.Create_an_ERC-20/README.md
> update: create-erc-20 skills

- software/32.Zig/README.md
> mod(zig): fixed 3.Calculator Documentation indent

- p2p/6.Create_a_proxy/README.md
- p2p/6.Create_a_proxy/utils/ProxyV1.t.sol
- p2p/6.Create_a_proxy/utils/ProxyV2.t.sol
- p2p/6.Create_a_proxy/utils/ProxyV3.t.sol
fix folder name and test files
> fix(p2p/proxy-workshop): fix errors

- p2p/10.IPFS_or_HTTP/README.md
I had deleted Adalina from this workshop authors, so i putted it back
> docs(README): put previous authors back

- p2p/11.Create_an_ERC-20_Tangem/README.md
- p2p/11.Create_an_ERC-20_Tangem/SETUP.md
- p2p/11.Create_an_ERC-20_Tangem/Solidity.md
- p2p/11.Create_an_ERC-20_Tangem/utils/.env
- p2p/11.Create_an_ERC-20_Tangem/utils/ERC20.sol
- p2p/11.Create_an_ERC-20_Tangem/utils/ERC20.t.sol
- p2p/11.Create_an_ERC-20_Tangem/utils/IERC20.sol
Add a workshop, create an erc20 with tangem
> add(p2p): create an erc20 with tangem
